version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tgadsbackend
    ports:
      - '3000:3000'
    depends_on:
      - clickhouse
      - redis
    restart: unless-stopped
    networks:
      - apinet
      - gateway
    env_file:
      - .env
    environment:
      - REDIS_TRACKING=${REDIS_TRACKING}
      - REDIS_STATS=${REDIS_STATS}
      - REDIS_GEO=${REDIS_GEO}
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    container_name: clickhouse
    ulimits:
      nofile: 262144
    restart: unless-stopped
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - chdata:/var/lib/clickhouse/
    networks:
      - apinet
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - rdsdata:/root/redis
      - cache:/data
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_DATABASES=16
    networks:
      - apinet
  nginx:
    build: "./nginx"
    networks:
      - apinet
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
volumes:
  cache:
  chdata:
  pgdata:
  rdsdata:
networks:
  apinet:
    name: apinet
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.32.0/24"
  gateway:
    name: gateway
    driver: bridge
